// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRentalCRUD.Data;

#nullable disable

namespace MovieRentalCRUD.Data.Migrations
{
    [DbContext(typeof(MovieRentalDBContext))]
    [Migration("20220108171318_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("MovieRentalCRUD.Data.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            MovieName = "Example Movie 0 Title",
                            MovieStock = 0,
                            MovieSummary = "Example Movie 0 Content"
                        },
                        new
                        {
                            MovieId = 2,
                            MovieName = "Example Movie 1 Title",
                            MovieStock = 0,
                            MovieSummary = "Example Movie 1 Content"
                        },
                        new
                        {
                            MovieId = 3,
                            MovieName = "Example Movie 2 Title",
                            MovieStock = 0,
                            MovieSummary = "Example Movie 2 Content"
                        },
                        new
                        {
                            MovieId = 4,
                            MovieName = "Example Movie 3 Title",
                            MovieStock = 0,
                            MovieSummary = "Example Movie 3 Content"
                        },
                        new
                        {
                            MovieId = 5,
                            MovieName = "Example Movie 4 Title",
                            MovieStock = 0,
                            MovieSummary = "Example Movie 4 Content"
                        },
                        new
                        {
                            MovieId = 6,
                            MovieName = "Example Movie 5 Title",
                            MovieStock = 0,
                            MovieSummary = "Example Movie 5 Content"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
